### ISSUE TITLE
Support for container membership properties

### ISSUE THREAD

**Issue by atextor** [AKSW/Xturtle#65]
RDF [container membership properties](http://www.w3.org/TR/2014/REC-rdf-syntax-grammar-20140225/#section-Syntax-list-elements) give a syntax error. The following minimal example should work:
```
@prefix : <http://example.com/foo#> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .

[ a rdf:Seq ;
  rdf:_1 "foo" ;
  rdf:_2 "bar"
] .
```

**Comment by nittka** [comment]
Yes, currently Xturtle cannot find a corresponding subject and hence shows a linking error. The simplest solution would be suppressing *any* linking errors for `rdf:_<number>` and `rdf:li`.

Could you (and possibly @seebi) comment on the following issues.
Is the proposed trivial solution sufficient? 

How about list properties outside collections?
```...
<x> rdf:_3 rdf:li .
...
```
I guess nobody would write that, but would you expect Xturtle to complain? What about incorrect numbering?
```
[ a rdf:Seq ;
  rdf:_2 "foo" ;
  rdf:_5 "bar"
] .
```
I assume list properties should never be linked, i.e. it should never be used as a subject which would cause successful linking.

Proposed first implementation:
* prevent list properties as subjects (validation error)
* suppress linking errors for list properties

Note that you can already use `<http://www.w3.org/1999/02/22-rdf-syntax-ns#_1>` instead of `rdf:_1` und disable linking validation for unknown URIs.

**Comment by seebi** [comment]
Another option is to add rdf:_1 to rdf:_100 to the core vocabulary :-)

**Comment by seebi** [comment]
maybe the best way is to introduce a new config option "not-resolved-namespaces" where the URI prefixes are listed where the linking errors are suppressed.

- http://www.w3.org/1999/02/22-rdf-syntax-ns#_
- http://dbpedia.org/resource/

beside that, a user maybe has other namespaces ...

**Comment by nittka** [comment]
Having a configurable list is indeed the most flexible solution. I'd do that as step 2 (the two prefixes you give would be hard coded first and would then be shipped as default. 
What about suppressing (error or warning?) list properties as subjects in order to prevent unintended linking?
Using URI-prefixes for the configuration has a drawback: rdf:li could be the prefix of a subject for which linking errors should be raised.

**Comment by atextor** [comment]
I think the most sane path would be suppressing linking errors for `rdf:_<number>` and `rdf:li` specifically, and introducing a configurable list (for dbpedia and the likes) with `rdf` *not* in it by default. Here's why: Although container membership properties outside collections don't make a whole lot of sense, there's nohing I see in the spec that prohibits this. `rdf:_<number>` are standard RDF properties and therefore should be usable as one sees fit. Jena processes them without complaint (as it should, IMHO):
```
$ cat test.ttl 
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
rdf:_2 a rdf:Resource .

$ riot --syntax=turtle --formatted=rdfxml test.ttl 
<rdf:RDF
    xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">
  <rdf:Resource rdf:about="http://www.w3.org/1999/02/22-rdf-syntax-ns#_2"/>
</rdf:RDF>
```
The same holds for incorrect numbering, arguably:
```
$ cat test2.ttl
@prefix : <http://example.com/foo#> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
[ a rdf:Seq;
  rdf:_2 "foo";
  rdf:_5 "bar"
].

$ riot --syntax=turtle --formatted=rdfxml test2.ttl 
<rdf:RDF
    xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
    xmlns="http://example.com/foo#">
  <rdf:Seq>
    <rdf:_5>bar</rdf:_5>
    <rdf:_2>foo</rdf:_2>
  </rdf:Seq>
</rdf:RDF>
```
A warning would be nice here, though.

I would not want to put `rdf` in the linking error suppression list, because of common typos (e.g., `rdf:label`).

**Comment by nittka** [comment]
The actual suggestion was to put rdf *followed by underscore* in the error suppression list.

I still have a problem with allowing rdf:_1 as subject for the following reason. If Xturtle allows it and I enable refactoring, e.g. renaming subject rdf:_1 to rdf:one, because of successful linking, all rdf:_1 will be affected.

I guess, I will end up with another validation config element - how to treat rdf list properties as subject...

**Comment by atextor** [comment]
I see, that makes sense. I think disallowing rdf:_n as subject won't pose any problems in real life.

**Comment by nittka** [comment]
As indicated, linking errors will be suppressed for list properties which are also not allowed as subjects.
If an unlinked URL starts with one of the prefixes configured via the validation preference page, no linking error is raised.

These changes are available on the snapshot update site.

**Comment by seebi** [comment]
works like a charm.

but I do not find the preference page ???

**Comment by nittka** [comment]
At the bottom of Preferences->Xturtle->Validation; it is not a separate preference page.

**Comment by seebi** [comment]
I do not have a Validation under Xturtle ...

<img width="627" alt="bildschirmfoto 2015-09-27 um 22 27 15" src="https://cloud.githubusercontent.com/assets/510452/10125048/0fa0bf14-6567-11e5-91ef-d17c927ec7f4.png">

**Comment by nittka** [comment]
It seems, you have opened the properties of the project, not the Eclipse Preference page (Menu Eclipse->Preferences or command +,).

**Comment by seebi** [comment]
correct ... found it :satisfied:

<img width="695" alt="bildschirmfoto 2015-09-28 um 08 25 30" src="https://cloud.githubusercontent.com/assets/510452/10129078/86c975ce-65ba-11e5-96dd-8a1b230279ab.png">
